// Standardized broker abstraction. Every broker (Alpaca, Webull, IBKR, and any future
// broker) implements this same interface so the trading/risk layer never talks to a
// broker-specific SDK directly. A PaperExecutionAdapter and a LiveBrokerAdapter for the
// same broker implement this identically — "live" is a config/credential change, not a
// different code path.

export type BrokerName = "ALPACA" | "WEBULL" | "IBKR" | "KRAKEN" | "COINBASE" | "TRADOVATE";
export type ExecutionMode = "PAPER" | "LIVE";

export interface BrokerCredentials {
  // Shape varies by broker (API key/secret pair, or OAuth tokens). Adapters validate
  // their own shape. Never logged, never sent to the frontend.
  [key: string]: string | undefined;
}

export interface BrokerAccountInfo {
  externalAccountId: string;
  accountType?: string;
  currency: string;
  cash: number;
  buyingPower: number;
  equity: number;
}

export interface BrokerPosition {
  symbol: string;
  quantity: number;
  avgPrice: number;
  marketValue?: number;
}

export type BrokerOrderSide = "BUY" | "SELL";
export type BrokerOrderType = "MARKET" | "LIMIT" | "STOP" | "STOP_LIMIT";
export type BrokerTimeInForce = "DAY" | "GTC" | "IOC" | "FOK" | "OPG" | "CLS";

export interface PlaceOrderRequest {
  clientRequestId: string; // idempotency key generated by BerylTerminal, not the broker
  symbol: string;
  side: BrokerOrderSide;
  type: BrokerOrderType;
  timeInForce: BrokerTimeInForce;
  quantity: number;
  limitPrice?: number;
  stopPrice?: number;
}

export interface BrokerOrderResult {
  externalOrderId: string;
  status: "ACCEPTED" | "REJECTED";
  rejectReason?: string;
}

export interface BrokerOrderState {
  externalOrderId: string;
  status: "NEW" | "PARTIALLY_FILLED" | "FILLED" | "CANCELLED" | "REJECTED";
  filledQuantity: number;
  avgFillPrice?: number;
}

export interface BrokerCapabilities {
  authentication: boolean;
  accountDiscovery: boolean;
  balances: boolean;
  buyingPower: boolean;
  positions: boolean;
  orders: boolean;
  executions: boolean;
  quotes: boolean;
  placeOrder: boolean;
  modifyOrder: boolean;
  cancelOrder: boolean;
  streamingAccountEvents: boolean;
  streamingOrderEvents: boolean;
}

// The interface every broker adapter (and the paper adapter) must implement.
export interface BrokerAdapter {
  readonly broker: BrokerName;
  readonly mode: ExecutionMode;
  readonly capabilities: BrokerCapabilities;

  authenticate(credentials: BrokerCredentials): Promise<void>;
  getAccount(): Promise<BrokerAccountInfo>;
  getPositions(): Promise<BrokerPosition[]>;
  getQuote(symbol: string): Promise<{ symbol: string; price: number; timestamp: string }>;

  placeOrder(req: PlaceOrderRequest): Promise<BrokerOrderResult>;
  modifyOrder(externalOrderId: string, changes: Partial<PlaceOrderRequest>): Promise<BrokerOrderResult>;
  cancelOrder(externalOrderId: string): Promise<{ status: "CANCELLED" | "ERROR"; reason?: string }>;
  getOrderState(externalOrderId: string): Promise<BrokerOrderState>;

  // Optional streaming — not every broker/tier supports this; callers should check capabilities first.
  streamOrderEvents?(onEvent: (state: BrokerOrderState) => void): Promise<() => void>; // returns an unsubscribe fn
}

export class BrokerNotConnectedError extends Error {
  constructor(broker: BrokerName) {
    super(`${broker} is not connected. Connect it from the broker menu before trading.`);
    this.name = "BrokerNotConnectedError";
  }
}

export class BrokerCapabilityError extends Error {
  constructor(broker: BrokerName, capability: string) {
    super(`${broker} does not support ${capability} in the current tier/mode.`);
    this.name = "BrokerCapabilityError";
  }
}
